apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-disk1
  namespace: python
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteMany
  cephfs:
  monitors:
    - "172.17.0.1:6789"
  user: admin
  secretRef:
    name: ceph-secret
  readOnly: false