apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: appclaim1
  namespace: python
spec:
  capacity:
  storage: 30Gi
  accessModes:
    - ReadWriteMany
  cephfs:
  user: admin
  secretRef:
    name: ceph-secret
  ReadOnly: false
