apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: appclaim1
  namespace: python
spec:
  capacity:
  storage: 50Gi
  accessModes:
    - ReadWriteMany
  cephfs:
  monitors:
    - "172.17.0.1:6789"
  user: admin
  secretRef:
    name: ceph-secret
  ReadOnly: false